

[global]

disableWatchdogWarning = false

showWarningOnDirectExecution = true



[client]

caching = true

displayEnabled = true


[runner]

magicEnabled = true

installTracer = false

fixMatplotlib = true


[server]

folderWatchBlacklist = ['']


headless = true

runOnSave = false

port = 8080

enableCORS = true


[browser]

serverAddress = "0.0.0.0"

gatherUsageStats = true

serverPort = 8080
